    <?php
    // No whitespace before this tag

    require_once 'db.php';
    require_once('vendor/tecnickcom/tcpdf/tcpdf.php');

    // Fetch users
    $stmt = $pdo->query("SELECT * FROM users");
    $users = $stmt->fetchAll();

    // Fetch books
    $stmtBooks = $pdo->query("SELECT * FROM books");
    $books = $stmtBooks->fetchAll();

    // Create PDF
    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Admin');
    $pdf->SetTitle('eBookStore Report');
    $pdf->SetSubject('Users and Books');

    $pdf->SetHeaderData('', 0, 'eBookStore Report', 'Generated by Admin Panel');
    $pdf->setHeaderFont(['helvetica', '', 10]);
    $pdf->setFooterFont(['helvetica', '', 8]);
    $pdf->SetMargins(15, 27, 15);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(TRUE, 25);
    $pdf->SetFont('helvetica', '', 12);

    $pdf->AddPage();

    // === Users Section ===
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 10, 'User Report', 0, 1, 'C');
    $pdf->Ln(5);

    // Users Table Header
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(10, 10, 'ID', 1);
    $pdf->Cell(50, 10, 'Name', 1);
    $pdf->Cell(70, 10, 'Email', 1);
    $pdf->Cell(30, 10, 'Verified', 1);
    $pdf->Ln();

    // Users Table Rows
    $pdf->SetFont('helvetica', '', 12);
    foreach ($users as $user) {
        $pdf->Cell(10, 10, $user['id'], 1);
        $pdf->Cell(50, 10, $user['name'], 1);
        $pdf->Cell(70, 10, $user['email'], 1);
        $pdf->Cell(30, 10, $user['is_verified'] ? 'Yes' : 'No', 1);
        $pdf->Ln();
    }

    // === Books Section ===
    $pdf->AddPage();
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 10, 'Book Report', 0, 1, 'C');
    $pdf->Ln(5);

    // Books Table Header
    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->Cell(10, 10, 'ID', 1, 0, 'C');
    $pdf->Cell(40, 10, 'Title', 1, 0, 'C');
    $pdf->Cell(30, 10, 'Author', 1, 0, 'C');
    $pdf->Cell(25, 10, 'Price', 1, 0, 'C');
    $pdf->Cell(35, 10, 'Category', 1, 0, 'C');
    $pdf->Cell(50, 10, 'File Path', 1, 1, 'C');

    // Books Table Rows
    $pdf->SetFont('helvetica', '', 10);
    foreach ($books as $book) {
        // Estimate line heights
        $lineHeight = 6;
        $cellHeights = [];
        $cellHeights[] = $pdf->getNumLines($book['title'], 40) * $lineHeight;
        $cellHeights[] = $pdf->getNumLines($book['author'], 30) * $lineHeight;
        $cellHeights[] = $pdf->getNumLines($book['category'], 35) * $lineHeight;
        $cellHeights[] = $pdf->getNumLines(basename($book['file_path']), 50) * $lineHeight;

        // Fix: ensure max gets a flat array
        $rowHeight = max(array_merge($cellHeights, [10]));

        // Draw cells
        $pdf->MultiCell(10, $rowHeight, $book['id'], 1, 'C', false, 0);
        $pdf->MultiCell(40, $rowHeight, $book['title'], 1, 'L', false, 0);
        $pdf->MultiCell(30, $rowHeight, $book['author'], 1, 'L', false, 0);
        $pdf->MultiCell(25, $rowHeight, number_format($book['price'], 2), 1, 'R', false, 0);
        $pdf->MultiCell(35, $rowHeight, $book['category'], 1, 'L', false, 0);
        $pdf->MultiCell(50, $rowHeight, basename($book['file_path']), 1, 'L', false, 1);
    }


    // Output
    $pdf->Output('ebookstore_report.pdf', 'I');
